steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image', '.' ]

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - |-
    echo "this is test"

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - |-
    echo "this is test"
    echo "this is test"
    
images:
- 'gcr.io/$PROJECT_ID/helloworld-image'
