steps:
- id: docker build
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image', '.' ]

- id: bash command test
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['echo','test']

- id: bash command test2
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - -c
  - |-
    echo "this is test"
    echo "this is test"
    
images:
- 'gcr.io/$PROJECT_ID/helloworld-image'
